apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: addon-operator
  namespace: olm
spec:
  sourceType: grpc
  publisher: Red Hat
  displayName: MTSRE Addon Operator
  image: quay.io/app-sre/addon-operator-index:main
