# To be used for local development and testing only
apiVersion: v1
kind: Service
metadata:
  name: addon-operator-metrics
  namespace: addon-operator
  labels:
    app: addon-operator-metrics-service
  # In production, the following annotation will make service-ca-operator to create a Secret called `metrics-server-cert` on the fly and manage its lifecycle
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: metrics-server-cert
spec:
  ports:
    - port: 8443
      name: https
      targetPort: 8443
    - port: 8080
      name: http  ## [only for dev/test purposes]
      targetPort: 8080
  selector:
    app.kubernetes.io/name: addon-operator
