apiVersion: v1
kind: Service
metadata:
  name: api-mock
  namespace: api-mock
  labels:
    app.kubernetes.io/name: api-mock
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: api-mock
---
apiVersion: v1
kind: Secret
metadata:
  name: api-mock
  namespace: api-mock
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths": {"cloud.openshift.com": {"auth": "THIS_IS_AN_API_TOKEN"}}}'
