apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: package-operator
spec:
  scopes:
  - Cluster
  phases:
  - name: crds
  - name: namespace
  - name: rbac
  - name: deploy
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: "True"
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  - probes:
    - condition:
        type: Established
        status: "True"
    selector:
      kind:
        group: apiextensions.k8s.io
        kind: CustomResourceDefinition
