apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: test-stub
spec:
  scopes:
  - Cluster
  - Namespaced
  phases:
  - name: namespace
  - name: deploy
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: "True"
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
test:
  template:
  - name: namespace-scope
    context:
      package:
        metadata:
          name: test
          namespace: test-ns
          annotations:
            package-operator.run/test-stub-image: test123
  - name: cluster-scope
    context:
      package:
        metadata:
          name: test
          annotations:
            package-operator.run/test-stub-image: test123
